#!/bin/bash

[ -f "./Gemfile" ] && bundle install -j8
[ -f "./package.json" ] && npm install
[ -f "./bower.json" ] && bower install
[ -f "./project.clj" ] && lein deps
[ -f "./pom.xml" ] && mvn dependency:resolve
[ -f "./composer.json" ] && composer install
